import { ProjectImages } from "./ProjectImages";

export const ProjectsInfo = [
    {
        name: "Graphy", 
        image: ProjectImages.GraphyImage,
        tags: "HTML, React, CSS",
        description: "Graphy is an online data simulation tool that allows users to simulate numerical data and compare in graphical format.",
        projectLink: "https://github.com/vermakartik/graphy",
        isLive: true,
        liveLink: "https://vermakartik.github.io/graphy",
    },
    {
        name: "AR Chess", 
        image: ProjectImages.ArChessImage,
        tags: "Android, Blender, Kotlin, Sceneform",
        description: "AR Chess is an Augmented Reality Based 3D Chess Application.",
        projectLink: "https://github.com/vermakartik/ArChess",
        isLive: false,
        liveLink: "",
    },
    {
        name: "AR Solar System", 
        image: ProjectImages.ArSolarSystemImage,
        tags: "Android, Blender, Kotlin, Sceneform",
        description: "This web project is a full-stack freelance project developed for CSA IGMC, Shimla. It includes both a front end and admin panel. It uses the latest technologies such as material UI, graphql, react.",
        projectLink: "https://github.com/vermakartik/ARSolarSystem",
        isLive: false,
        liveLink: "",
    },
    {
        name: "CSA IGMC", 
        image: ProjectImages.CsaIgmcImage,
        tags: "React, Graph QL, Apollo, Material UI, Express, Mongoose, MongoDB",
        description: "Graphy is an online data simulation tool that allows users to simulate numerical data and compare in graphical format.",
        projectLink: "https://github.com/csaigmc",
        isLive: true,
        liveLink: "https://igmccsa.in/",
    },
    {
        name: "Plax", 
        image: ProjectImages.PlaxProjectImage,
        tags: "HTML, CSS, UI React",
        description: "This web project is to enhance my skills on UI design. It showcases my projects using the parallax effect with a little description.",
        projectLink: "https://github.com/vermakartik/plax",
        isLive: true,
        liveLink: "https://vermakartik.github.io/plax/",
    },
    {
        name: "Profo", 
        image: ProjectImages.ProfoImage,
        tags: "Python, Django, HTML, CSS, JS",
        description: "This web project is specifically designed to digitize the university tests. It is an online test platform that allows teachers to create new tests and students can then attempt the online tests.",
        projectLink: "https://github.com/vermakartik/Profo",
        isLive: false,
        liveLink: "",
    },
    {
        name: "Edito", 
        image: ProjectImages.EditorImage,
        tags: "React, Express.js, mongodb, mongoose",
        description: "This is a personal blog inspired from ines.io. The blog shows my personal experiences and thoughts.",
        projectLink: "https://github.com/vermakartik/profile",
        isLive: true,
        liveLink: "https://vermakartik.github.io/profile/#/posts",
    },
    {
        name: "HillShare", 
        image: ProjectImages.HillShareImage,
        tags: "Android, Firebase, Java, XML",
        description: "It allows users to share their personal vehicles saving fuel and making transport more economical. Users share in app if they are travelling somewhere and other users can join in to share a ride.",
        projectLink: "https://github.com/vermakartik/RiderApp",
        isLive: false,
        liveLink: "",
    },
    {
        name: "The Money Game", 
        image: ProjectImages.MoneyGameImage,
        tags: "Javascript, Three.js, PIE.js",
        description: "An animation developed using three.js developed for class 2 students that allows them to interactively learn how money works. This was developed as a part of the ekshiksha project.",
        projectLink: "https://github.com/vermakartik/The-Money-Game",
        isLive: true,
        liveLink: "https://www.it.iitb.ac.in/summerinternship2018/activity_src/0MO84FuysWRAqPNAPH0ctg/wi1XrHwwRTU2L41rf6fO8w/Experiment/index.jsp",
    },
    {
        name: "Fun With Resistors", 
        image: ProjectImages.ResistanceGameImage,
        tags: "Javascript, Three.js, PIE.js",
        description: "An animation developed using three.js developed for class 8 (and above) students that allows them to interactively learn how to join resistances in series and parallel.",
        projectLink: "https://github.com/vermakartik/Fun-With-resistors",
        isLive: true,
        liveLink: "https://www.it.iitb.ac.in/summerinternship2018/activity_src/0MO84FuysWRAqPNAPH0ctg/hYGN6m-wk7__e2ZP96dGiw/Experiment/index.jsp",
    },
    {
        name: "Magnets", 
        image: ProjectImages.MagnetGameImage,
        tags: "Javascript, Three.js, PIE.js",
        description: "An animation developed using three.js developed for students to allow them to interactively learn how two magnets repel and attract depending on their magnetism.",
        projectLink: "https://github.com/vermakartik/Magnets",
        isLive: true,
        liveLink: "https://www.it.iitb.ac.in/summerinternship2018/activity_src/0MO84FuysWRAqPNAPH0ctg/XKIEzUcb_xms26EWchVlzw/Experiment/index.jsp",
    },
    {
        name: "GUI Term", 
        image: ProjectImages.GuiTermImage,
        tags: "ruby, bash, shell",
        description: "gui-term is a simple library or gem for creating gui for terminal in ruby. It is a simple library that allows developers to create animations in true color using primitive shapes.",
        projectLink: "https://github.com/vermakartik/gui-term",
        isLive: false,
        liveLink: "",
    },
    {
        name: "Neural Style Transfer", 
        image: ProjectImages.StyleTransferImage,
        tags: "Python, Keras, CNNs",
        description: "Using Deep Learning and CNNs for Artistic Imaging. Based on Gatys et al. research paper and Harish Narayanan tutorial on Neural Style Transfer",
        projectLink: "https://github.com/vermakartik/Neural-Style-Transfer",
        isLive: false,
        liveLink: "",
    },
    {
        name: "HillShare", 
        image: ProjectImages.HillShareImage,
        tags: "Android, Firebase, Java, XML",
        description: "It allows users to share their personal vehicles saving fuel and making transport more economical. Users share in app if they are travelling somewhere and other users can join in to share a ride.",
        projectLink: "https://github.com/vermakartik/RiderApp",
        isLive: false,
        liveLink: "",
    },
    {
        name: "Digit Recognition", 
        image: ProjectImages.DigitRecogImage,
        tags: "Python, Keras, CNNs, Android",
        description: "Using Deep Learning and CNNs for developing a simple real time digit recognizer app using the mnist data set.",
        projectLink: "https://github.com/vermakartik/digit-recognition-app",
        isLive: false,
        liveLink: "",
    },
    {
        name: "Snakky", 
        image: ProjectImages.SnakkyImage,
        tags: "Python, Pygames",
        description: "A simple snake game where snake is controlled by the user and grows as it eats the apples.",
        projectLink: "https://github.com/vermakartik/Snake-AI",
        isLive: false,
        liveLink: "",
    },
]