import {results } from 'Components/Resume/ResumeImages'

export const SkillInfo = [
    {name: "Unity", imageIcon: results.UnityImage},
    {name: "C#", imageIcon: results.CSharpImage},
    {name: "Blender", imageIcon: results.BlenderImage},
    {name: "Android", imageIcon: results.AndroidImage},
    {name: "Apollo", imageIcon: results.ApolloImage},
    {name: "C++", imageIcon: results.CPPImage},
    {name: "C", imageIcon: results.CPImage},
    {name: "CSS3", imageIcon: results.CSS3Image},
    {name: "Django", imageIcon: results.DjangoImage},
    {name: "Firebase", imageIcon: results.FirebaseImage},
    {name: "Git", imageIcon: results.GitImage},
    {name: "Github", imageIcon: results.GithubImage},
    {name: "GraphQL", imageIcon: results.GraphQLImage},
    {name: "HTML", imageIcon: results.HTMLImage},
    {name: "Java", imageIcon: results.JavaImage},
    {name: "Javascript", imageIcon: results.JavascriptImage},
    {name: "Keras", imageIcon: results.KerasImage},
    {name: "Linux", imageIcon: results.LinuxImage},
    {name: "MaterialUI", imageIcon: results.MaterialUIImage},
    {name: "Mongodb", imageIcon: results.MongodbImage},
    {name: "MongooseUI", imageIcon: results.MongooseUIImage},
    {name: "MySQL", imageIcon: results.MySQLImage},
    {name: "Nodejs", imageIcon: results.NodejsImage},
    {name: "Python", imageIcon: results.PythonImage},
    {name: "React", imageIcon: results.ReactImage},
    {name: "Redux", imageIcon: results.ReduxImage},
    {name: "Ruby", imageIcon: results.RubyImage},
    {name: "XML", imageIcon: results.XMLImage},
    {name: "Leadership", imageIcon: results.LeadershipImage},
    {name: "TeamWork", imageIcon: results.TeamWorkImage}

]